/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlkh.testView;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import qlkh.utils.custombarchart.ChartItem;
import qlkh.utils.custombarchart.BarChartItems;
import qlkh.utils.custombarchart.BarChart_AWT;
import qlkh.utils.custombarchart.PieChart_AWT;

/**
 *
 * @author GIANG
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    private static boolean isFirstTime = true;
    private static final String[] cbbItem1 = {"7 ngày gần nhất", "6 tháng gần nhất ", "5 năm gần nhất"};
    private static final String[] cbbItem3 = {"7 ngày gần nhất", "3 tháng gần nhất "};

    private static final int oneMilion = 100000;

    public NewJFrame1() {
        initComponents();

        for (String cbbItem11 : cbbItem1) {
            cbbTable1.addItem(cbbItem11);
        }
        for (String cbbItem13 : cbbItem3) {
            cbbTable3.addItem(cbbItem13);
        }
        tablePanel1.add(new JPanel());
        tablePanel3.add(new JPanel());
        isFirstTime = false;
         JPanel panel = createPieChartTable(getListItemsPieChartTable2(),"Lượng hàng tồn kho theo danh mục");
            tablePanel2.add(panel);
           
    }

    public List<BarChartItems> getListItems() {
        List<BarChartItems> items = new ArrayList<>();
        for (int i = 1; i <= 6; i++) {
            ChartItem item1 = new ChartItem("Import Detail", ((i + 0.5) * 2000000) / oneMilion);
            ChartItem item2 = new ChartItem("Export Detail", ((i + 0.5) * 1009009) / oneMilion);
            BarChartItems item = new BarChartItems(String.valueOf(i), item1, item2);
            items.add(item);
        }
        return items;
    }

    public List<BarChartItems> getListItemsTable3() {
        List<BarChartItems> items = new ArrayList<>();
        for (int i = 1; i <= 7; i++) {
            ChartItem item1 = null;
            ChartItem item2 = new ChartItem("Profit detail", ((i + 0.5) * 1009009) / oneMilion);
            BarChartItems item = new BarChartItems(String.valueOf(i), item1, item2);
            items.add(item);
        }
        return items;
    }

    public List<BarChartItems> getListItemsTable31() {
        List<BarChartItems> items = new ArrayList<>();
        for (int i = 1; i <= 6; i++) {
            ChartItem item1 = null;
            ChartItem item2 = new ChartItem("Profit detail-v1", ((i + 0.5) * 1009009) / oneMilion);
            BarChartItems item = new BarChartItems(String.valueOf(i), item1, item2);
            items.add(item);
        }
        return items;
    }

    public List<ChartItem> getListItemsPieChartTable2() {
        List<ChartItem> items = new ArrayList<>();
        items.add(new ChartItem("Thuy san", 100));
        items.add(new ChartItem("Vi tinh", 300));
        items.add(new ChartItem(" cong ngiep", 240));
        return items;
    }

    public List<BarChartItems> getListItems1() {
        List<BarChartItems> items = new ArrayList<>();
        for (int i = 1; i <= 6; i++) {
            ChartItem item1 = new ChartItem("Import Detail-lv1", ((i + 0.5) * 2000000) / oneMilion);
            ChartItem item2 = new ChartItem("Export Detail-lv1", ((i + 0.5) * 1009009) / oneMilion);
            BarChartItems item = new BarChartItems(String.valueOf(i), item1, item2);
            items.add(item);
        }
        return items;
    }

    public List<BarChartItems> getListItems2() {
        List<BarChartItems> items = new ArrayList<>();
        for (int i = 1; i <= 6; i++) {
            ChartItem item1 = new ChartItem("Import Detail-lv2", ((i + 0.5) * 2000000) / oneMilion);
            ChartItem item2 = new ChartItem("Export Detail-lv2", ((i + 0.5) * 1009009) / oneMilion);
            BarChartItems item = new BarChartItems(String.valueOf(i), item1, item2);
            items.add(item);
        }
        return items;
    }

    public JPanel createBarChartTable(List<BarChartItems> items, String tittle, String horizontiltle, String verticalTitle) {
        String title1 = "Car Usage Statistics";
        BarChart_AWT chart = new BarChart_AWT("title",
                tittle, items, horizontiltle, verticalTitle);
        return chart.getContentPage();
    }
    public JPanel createPieChartTable(List<ChartItem> items, String tittle) {
        String title1 = "Car Usage Statistics";
        PieChart_AWT chart = new  PieChart_AWT(tittle,items);
        return chart.getContentPage();
    }

    public void addTablePanel1(JPanel panel) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        upPanel = new javax.swing.JPanel();
        tableParentPanel1 = new javax.swing.JPanel();
        tablePanel1 = new javax.swing.JPanel();
        cbbTable1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        tablePanel2 = new javax.swing.JPanel();
        downPanel = new javax.swing.JPanel();
        tableParentPanel3 = new javax.swing.JPanel();
        cbbTable3 = new javax.swing.JComboBox();
        tablePanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        tablePanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        main.setPreferredSize(new java.awt.Dimension(1000, 721));
        main.setLayout(new javax.swing.BoxLayout(main, javax.swing.BoxLayout.PAGE_AXIS));

        tablePanel1.setLayout(new java.awt.CardLayout());

        cbbTable1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbTable1ItemStateChanged(evt);
            }
        });

        jLabel1.setText("Biểu đồ doanh thu và chi phí");

        javax.swing.GroupLayout tableParentPanel1Layout = new javax.swing.GroupLayout(tableParentPanel1);
        tableParentPanel1.setLayout(tableParentPanel1Layout);
        tableParentPanel1Layout.setHorizontalGroup(
            tableParentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableParentPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                .addComponent(cbbTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
            .addGroup(tableParentPanel1Layout.createSequentialGroup()
                .addComponent(tablePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        tableParentPanel1Layout.setVerticalGroup(
            tableParentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableParentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableParentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbTable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(tablePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        tablePanel2.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout upPanelLayout = new javax.swing.GroupLayout(upPanel);
        upPanel.setLayout(upPanelLayout);
        upPanelLayout.setHorizontalGroup(
            upPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upPanelLayout.createSequentialGroup()
                .addComponent(tableParentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        upPanelLayout.setVerticalGroup(
            upPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableParentPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(upPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tablePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        main.add(upPanel);

        cbbTable3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbTable3ItemStateChanged(evt);
            }
        });

        tablePanel3.setLayout(new java.awt.CardLayout());

        jLabel2.setText("Lãi xuất");

        javax.swing.GroupLayout tableParentPanel3Layout = new javax.swing.GroupLayout(tableParentPanel3);
        tableParentPanel3.setLayout(tableParentPanel3Layout);
        tableParentPanel3Layout.setHorizontalGroup(
            tableParentPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableParentPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93)
                .addComponent(cbbTable3, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
            .addComponent(tablePanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        tableParentPanel3Layout.setVerticalGroup(
            tableParentPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tableParentPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableParentPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbTable3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tablePanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout tablePanel4Layout = new javax.swing.GroupLayout(tablePanel4);
        tablePanel4.setLayout(tablePanel4Layout);
        tablePanel4Layout.setHorizontalGroup(
            tablePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
        );
        tablePanel4Layout.setVerticalGroup(
            tablePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 325, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout downPanelLayout = new javax.swing.GroupLayout(downPanel);
        downPanel.setLayout(downPanelLayout);
        downPanelLayout.setHorizontalGroup(
            downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downPanelLayout.createSequentialGroup()
                .addComponent(tableParentPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tablePanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        downPanelLayout.setVerticalGroup(
            downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tableParentPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, downPanelLayout.createSequentialGroup()
                .addGap(0, 37, Short.MAX_VALUE)
                .addComponent(tablePanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        main.add(downPanel);

        jPanel1.add(main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbTable1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbTable1ItemStateChanged
        String cbb1Text = cbbTable1.getSelectedItem().toString();
        CardLayout layout = (CardLayout) tablePanel1.getLayout();
        if (cbb1Text.equals(cbbItem1[0])) {
            JPanel panel = createBarChartTable(getListItems(), cbb1Text, cbb1Text, cbb1Text);
            tablePanel1.add(panel, cbbItem1[0]);
            layout.show(tablePanel1, cbbItem1[0]);
        } else if (cbb1Text.equals(cbbItem1[1]) && isFirstTime == false) {
            JPanel panel = createBarChartTable(getListItems(), cbb1Text, cbb1Text, cbb1Text);
            tablePanel1.add(panel, cbbItem1[1]);
            layout.show(tablePanel1, cbbItem1[1]);
        } else if (cbb1Text.equals(cbbItem1[2]) && isFirstTime == false) {
            JPanel panel = createBarChartTable(getListItems1(), cbb1Text, cbb1Text, cbb1Text);
            tablePanel1.add(panel, cbbItem1[2]);
            layout.show(tablePanel1, cbbItem1[2]);
        }
    }//GEN-LAST:event_cbbTable1ItemStateChanged

    private void cbbTable3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbTable3ItemStateChanged
        String cbb1Text = cbbTable3.getSelectedItem().toString();
        CardLayout layout = (CardLayout) tablePanel3.getLayout();
        if (cbb1Text.equals(cbbItem3[0])) {
            JPanel panel = createBarChartTable(getListItemsTable3(), cbb1Text, cbb1Text, cbb1Text);
            tablePanel3.add(panel, cbbItem3[0]);
            layout.show(tablePanel3, cbbItem3[0]);
        } else if (cbb1Text.equals(cbbItem3[1]) && isFirstTime == false) {
            JPanel panel = createBarChartTable(getListItemsTable31(), cbb1Text, cbb1Text, cbb1Text);
            tablePanel3.add(panel, cbbItem3[1]);
            layout.show(tablePanel3, cbbItem3[1]);
        }
    }//GEN-LAST:event_cbbTable3ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbbTable1;
    private javax.swing.JComboBox cbbTable3;
    private javax.swing.JPanel downPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel main;
    private javax.swing.JPanel tablePanel1;
    private javax.swing.JPanel tablePanel2;
    private javax.swing.JPanel tablePanel3;
    private javax.swing.JPanel tablePanel4;
    private javax.swing.JPanel tableParentPanel1;
    private javax.swing.JPanel tableParentPanel3;
    private javax.swing.JPanel upPanel;
    // End of variables declaration//GEN-END:variables
}
