/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlkh.testView;

import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import qlkh.utils.custombarchart.BarChartItem;
import qlkh.utils.custombarchart.BarChartItems;
import qlkh.utils.custombarchart.BarChart_AWT;

/**
 *
 * @author GIANG
 */
public class NewJFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame1
     */
    private static final String[] cbbItem1 = {"7 ngày gần nhất", "6 tháng gần nhất ", "5 năm gần nhất"};
private static final int oneMilion = 100000;
    public NewJFrame1() {
        initComponents();

        for (String cbbItem11 : cbbItem1) {
            cbbTable1.addItem(cbbItem11);
        }
        tablePanel1.add(new JPanel());
    }

    public List<BarChartItems> getListItems() {
        List<BarChartItems> items = new ArrayList<>();
        for (int i = 1; i <= 6; i++) {
            BarChartItem item1 = new BarChartItem(((i + 0.5) * 2000000)/oneMilion, "Import Detail");
            BarChartItem item2 = new BarChartItem(((i + 0.5) * 1009009)/oneMilion, "Export Detail");
            BarChartItems item = new BarChartItems(String.valueOf(i), item1, item2);
            items.add(item);
        }
        return items;
    }

    public List<BarChartItems> getListItems1() {
        List<BarChartItems> items = new ArrayList<>();
        for (int i = 1; i <= 6; i++) {
            BarChartItem item1 = new BarChartItem(((i + 0.5) * 2000000)/oneMilion, "Import Detail-lv1");
            BarChartItem item2 = new BarChartItem(((i + 0.5) * 1009009)/oneMilion, "Export Detail-lv1");
            BarChartItems item = new BarChartItems(String.valueOf(i), item1, item2);
            items.add(item);
        }
        return items;
    }
     public List<BarChartItems> getListItems2() {
        List<BarChartItems> items = new ArrayList<>();
        for (int i = 1; i <= 6; i++) {
            BarChartItem item1 = new BarChartItem(((i + 0.5) * 2000000)/oneMilion, "Import Detail-lv2");
            BarChartItem item2 = new BarChartItem(((i + 0.5) * 1009009)/oneMilion, "Export Detail-lv2");
            BarChartItems item = new BarChartItems(String.valueOf(i), item1, item2);
            items.add(item);
        }
        return items;
    }

    public JPanel createTable1(List<BarChartItems> items, String tittle, String horizontiltle, String verticalTitle) {
        String title1 = "Car Usage Statistics";

        BarChart_AWT chart = new BarChart_AWT("title",
                tittle, items, horizontiltle, verticalTitle);
        return chart.getContentPage();
    }

    public void addTablePanel1(JPanel panel) {

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        main = new javax.swing.JPanel();
        upPanel = new javax.swing.JPanel();
        tableParentPanel1 = new javax.swing.JPanel();
        tablePanel1 = new javax.swing.JPanel();
        cbbTable1 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        tablePanel2 = new javax.swing.JPanel();
        downPanel = new javax.swing.JPanel();
        tablePanel3 = new javax.swing.JPanel();
        tablePanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        main.setBackground(new java.awt.Color(153, 204, 0));
        main.setPreferredSize(new java.awt.Dimension(1000, 721));
        main.setLayout(new javax.swing.BoxLayout(main, javax.swing.BoxLayout.PAGE_AXIS));

        upPanel.setBackground(new java.awt.Color(51, 51, 0));

        tablePanel1.setLayout(new java.awt.CardLayout());

        cbbTable1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbbTable1ItemStateChanged(evt);
            }
        });

        jLabel1.setText("Biểu đồ doanh thu và chi phí");

        javax.swing.GroupLayout tableParentPanel1Layout = new javax.swing.GroupLayout(tableParentPanel1);
        tableParentPanel1.setLayout(tableParentPanel1Layout);
        tableParentPanel1Layout.setHorizontalGroup(
            tableParentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableParentPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(cbbTable1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
        tableParentPanel1Layout.setVerticalGroup(
            tableParentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tableParentPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(tableParentPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbTable1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tablePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout tablePanel2Layout = new javax.swing.GroupLayout(tablePanel2);
        tablePanel2.setLayout(tablePanel2Layout);
        tablePanel2Layout.setHorizontalGroup(
            tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        tablePanel2Layout.setVerticalGroup(
            tablePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout upPanelLayout = new javax.swing.GroupLayout(upPanel);
        upPanel.setLayout(upPanelLayout);
        upPanelLayout.setHorizontalGroup(
            upPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(upPanelLayout.createSequentialGroup()
                .addComponent(tableParentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tablePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        upPanelLayout.setVerticalGroup(
            upPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, upPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(upPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tablePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tableParentPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, Short.MAX_VALUE)))
        );

        main.add(upPanel);

        downPanel.setBackground(new java.awt.Color(0, 204, 51));

        tablePanel3.setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout tablePanel3Layout = new javax.swing.GroupLayout(tablePanel3);
        tablePanel3.setLayout(tablePanel3Layout);
        tablePanel3Layout.setHorizontalGroup(
            tablePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 603, Short.MAX_VALUE)
        );
        tablePanel3Layout.setVerticalGroup(
            tablePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        tablePanel4.setBackground(new java.awt.Color(0, 102, 0));

        javax.swing.GroupLayout tablePanel4Layout = new javax.swing.GroupLayout(tablePanel4);
        tablePanel4.setLayout(tablePanel4Layout);
        tablePanel4Layout.setHorizontalGroup(
            tablePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 391, Short.MAX_VALUE)
        );
        tablePanel4Layout.setVerticalGroup(
            tablePanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout downPanelLayout = new javax.swing.GroupLayout(downPanel);
        downPanel.setLayout(downPanelLayout);
        downPanelLayout.setHorizontalGroup(
            downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(downPanelLayout.createSequentialGroup()
                .addComponent(tablePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(tablePanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        downPanelLayout.setVerticalGroup(
            downPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablePanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, downPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(tablePanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        main.add(downPanel);

        jPanel1.add(main);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1004, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 727, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbTable1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbbTable1ItemStateChanged
  String cbb1Text = cbbTable1.getSelectedItem().toString();

        if (cbb1Text.equals(cbbItem1[0])) {
            JPanel panel = createTable1(getListItems(), cbb1Text, cbb1Text, cbb1Text);
            tablePanel1.add(panel, cbbItem1[0]);
            CardLayout layout = (CardLayout) tablePanel1.getLayout();
            layout.show(tablePanel1, cbbItem1[0]);
        }
        else if (cbb1Text.equals(cbbItem1[1])) {
            JPanel panel = createTable1(getListItems(), cbb1Text, cbb1Text, cbb1Text);
            tablePanel1.add(panel, cbbItem1[1]);
            CardLayout layout = (CardLayout) tablePanel1.getLayout();
            layout.show(tablePanel1, cbbItem1[1]);
        } else {
            JPanel panel = createTable1(getListItems1(), cbb1Text, cbb1Text, cbb1Text);
            tablePanel1.add(panel, cbbItem1[2]);
            CardLayout layout = (CardLayout) tablePanel1.getLayout();
            layout.show(tablePanel1, cbbItem1[2]);

        }

    }//GEN-LAST:event_cbbTable1ItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbbTable1;
    private javax.swing.JPanel downPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel main;
    private javax.swing.JPanel tablePanel1;
    private javax.swing.JPanel tablePanel2;
    private javax.swing.JPanel tablePanel3;
    private javax.swing.JPanel tablePanel4;
    private javax.swing.JPanel tableParentPanel1;
    private javax.swing.JPanel upPanel;
    // End of variables declaration//GEN-END:variables
}
