/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlkh.testView;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.ResourceBundle;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.TableModel;
import qlkh.entities.Users;
import qlkh.views.IView;
import qlkh.utils.Constants;
import qlkh.utils.pagination.ObjectTableModel;
import qlkh.utils.pagination.PaginatedTableDecorator;
import qlkh.utils.pagination.PaginationDataProvider;

/**
 *
 * @author GIANG
 */
public class ReportViewFrame extends javax.swing.JFrame  {

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userRoleMainPanel = new javax.swing.JPanel();
        mainPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        subPanelLeftUp = new javax.swing.JPanel();
        tablePanel0 = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        subPanelLeftDown = new javax.swing.JPanel();
        tablePanel2 = new javax.swing.JPanel();
        cbbReport2 = new javax.swing.JComboBox();
        subPanelLefDown = new javax.swing.JPanel();
        tablePanel3 = new javax.swing.JPanel();
        cbbReport3 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userRoleMainPanel.setBackground(new java.awt.Color(255, 255, 255));

        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.PAGE_AXIS));

        leftPanel.setBackground(new java.awt.Color(255, 153, 204));
        leftPanel.setLayout(new javax.swing.BoxLayout(leftPanel, javax.swing.BoxLayout.LINE_AXIS));

        subPanelLeftUp.setBackground(new java.awt.Color(255, 153, 51));

        tablePanel0.setBackground(new java.awt.Color(255, 204, 0));

        javax.swing.GroupLayout tablePanel0Layout = new javax.swing.GroupLayout(tablePanel0);
        tablePanel0.setLayout(tablePanel0Layout);
        tablePanel0Layout.setHorizontalGroup(
            tablePanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 972, Short.MAX_VALUE)
        );
        tablePanel0Layout.setVerticalGroup(
            tablePanel0Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout subPanelLeftUpLayout = new javax.swing.GroupLayout(subPanelLeftUp);
        subPanelLeftUp.setLayout(subPanelLeftUpLayout);
        subPanelLeftUpLayout.setHorizontalGroup(
            subPanelLeftUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablePanel0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        subPanelLeftUpLayout.setVerticalGroup(
            subPanelLeftUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablePanel0, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        leftPanel.add(subPanelLeftUp);

        mainPanel.add(leftPanel);

        rightPanel.setBackground(new java.awt.Color(0, 255, 102));
        rightPanel.setLayout(new javax.swing.BoxLayout(rightPanel, javax.swing.BoxLayout.LINE_AXIS));

        subPanelLeftDown.setBackground(new java.awt.Color(0, 255, 255));

        tablePanel2.setBackground(new java.awt.Color(255, 204, 0));
        tablePanel2.setLayout(new java.awt.CardLayout());

        cbbReport2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbReport2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanelLeftDownLayout = new javax.swing.GroupLayout(subPanelLeftDown);
        subPanelLeftDown.setLayout(subPanelLeftDownLayout);
        subPanelLeftDownLayout.setHorizontalGroup(
            subPanelLeftDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
            .addGroup(subPanelLeftDownLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(cbbReport2, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subPanelLeftDownLayout.setVerticalGroup(
            subPanelLeftDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelLeftDownLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(cbbReport2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );

        rightPanel.add(subPanelLeftDown);

        subPanelLefDown.setBackground(new java.awt.Color(0, 204, 102));

        tablePanel3.setBackground(new java.awt.Color(255, 204, 0));
        tablePanel3.setLayout(new java.awt.CardLayout());

        cbbReport3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbReport3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout subPanelLefDownLayout = new javax.swing.GroupLayout(subPanelLefDown);
        subPanelLefDown.setLayout(subPanelLefDownLayout);
        subPanelLefDownLayout.setHorizontalGroup(
            subPanelLefDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tablePanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 486, Short.MAX_VALUE)
            .addGroup(subPanelLefDownLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(cbbReport3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subPanelLefDownLayout.setVerticalGroup(
            subPanelLefDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelLefDownLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(cbbReport3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tablePanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );

        rightPanel.add(subPanelLefDown);

        mainPanel.add(rightPanel);

        javax.swing.GroupLayout userRoleMainPanelLayout = new javax.swing.GroupLayout(userRoleMainPanel);
        userRoleMainPanel.setLayout(userRoleMainPanelLayout);
        userRoleMainPanelLayout.setHorizontalGroup(
            userRoleMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        userRoleMainPanelLayout.setVerticalGroup(
            userRoleMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 625, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userRoleMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(userRoleMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbbReport3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbReport3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbReport3ActionPerformed

    private void cbbReport2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbReport2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbReport2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbbReport2;
    private javax.swing.JComboBox cbbReport3;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel subPanelLefDown;
    private javax.swing.JPanel subPanelLeftDown;
    private javax.swing.JPanel subPanelLeftUp;
    private javax.swing.JPanel tablePanel0;
    private javax.swing.JPanel tablePanel2;
    private javax.swing.JPanel tablePanel3;
    private javax.swing.JPanel userRoleMainPanel;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form GiangTestFrame
     */
    ResourceBundle bundle;
    private static final int[] pageSizes = new int[]{10, 20, 50, 75, 100};
    private static final int defaultPageSize = pageSizes[0];
    //button để hiện phân trang maximum 7
    private static final int maxPagingCompToShow = 7;
    private static List<Users> users = new ArrayList<>();

    JTable tblUsers;
    PaginatedTableDecorator<Users> paginatedDecorator;

    public ReportViewFrame() {
        //  Locale local = Utils.getLocale();
        Locale local = Locale.getDefault();
        setResourceBundle(local);
        initComponents();

    }
    // Show view with list Suplier on Suplier Table

    // Show view with list Suplier on Suplier Table
    public void showView() {
        this.setVisible(true);
       
    }

 
    // Set ResourceBundle to this view
    private void setResourceBundle(Locale locale) {
        //Set Resources Bundle theo local 
        bundle = ResourceBundle.getBundle("qlkh/utils/languages", locale);

    }

   
}
