/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlkh;

import java.awt.Color;
import java.awt.event.ActionListener;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.ResourceBundle;
import java.util.Scanner;
import java.util.Set;
import javax.swing.JOptionPane;
import qlkh.controller.SignInController;
import qlkh.entities.Users;
import qlkh.utils.Constants;
import qlkh.utils.Utils;

/**
 *
 * @author user
 */
public class SignIn extends javax.swing.JFrame {

    private static Locale local;
    // đặt biến ResourcesBundle toàn cục
    private static ResourceBundle bundle;

    public SignIn(Locale local) {
//        local = Locale.getDefault();
        
        this.local = local;
        setResourceBundle(local);
        setValueComboxLanguages();
        initComponents();
        setLocationRelativeTo(null);
    }

    //hàm lấy bundle trong file languages
    private void setResourceBundle(Locale locale) {
        //Set Resources Bundle theo local 
        bundle = ResourceBundle.getBundle("qlkh/utils/languages", locale);

    }

    //hàm lấy về locale trong comboxbox
    public String getMyLocaleInCombobox() {
        // Trả về Item của combobox đang được chọn
        return (String) chkBoxMyLocale.getSelectedItem();
    }

    //hàm thêm sự kiện cho button signIn
    public void addBtnSignInActionListener(ActionListener listener) {
        btnSignIn.addActionListener(listener);
    }
    
    //hàm thêm sự kiện cho button signup
    public void addBtnSignUpActionListener(ActionListener listener) {
        btnSignUp.addActionListener(listener);
    }
    
    //hàm thêm sự kiện cho checkbox rememberpassowrd
    public void addCheckBoxRemeberPassword(ActionListener listner) {
        ckRememberPass.addActionListener(listner);
    }
    
    //hàm thêm sự kiejn cho combox languages
    public void addMyLocaleStateChanged(ActionListener listener) {
        //thêm sự kiện ActionListener cho comboBox
        chkBoxMyLocale.addActionListener(listener);
    }
    //hàm thêm sự kiện cho forgot password
    public void addBtnForgotPassActionListener(ActionListener listener){
        btnForgotPassword.addActionListener(listener);
        System.out.println("ádf");
    }
    
    //hàm đóng view
    public void closeLoginView() {
        this.dispose();
    }
    
    //hàm show signIn
    public void showView() {
        this.setVisible(true);
        
    }
    //hàm set value cho combobox
    private void setValueComboxLanguages(){
        System.out.println(local.getCountry());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        siUsername = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        siPassword = new javax.swing.JPasswordField();
        btnSignUp = new keeptoo.KButton();
        btnSignIn = new keeptoo.KButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        chkBoxMyLocale = new javax.swing.JComboBox();
        ckRememberPass = new javax.swing.JCheckBox();
        errPassword = new javax.swing.JLabel();
        errUsername = new javax.swing.JLabel();
        btnForgotPassword = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        kGradientPanel1.setEndColor(new java.awt.Color(0, 204, 204));
        kGradientPanel1.setGradientFocus(600);
        kGradientPanel1.setStartColor(new java.awt.Color(153, 0, 153));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/qlkh/icons/male-user-70.png"))); // NOI18N
        kGradientPanel1.add(jLabel1);
        jLabel1.setBounds(420, 70, 70, 70);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel2.setText(bundle.getString("signInPassword"));
        kGradientPanel1.add(jLabel2);
        jLabel2.setBounds(250, 290, 90, 27);

        siUsername.setBackground(new Color(0,0,0,0));
        siUsername.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        siUsername.setForeground(new java.awt.Color(153, 153, 153));
        siUsername.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        siUsername.setCaretColor(new java.awt.Color(255, 255, 255));
        siUsername.setOpaque(false);
        siUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siUsernameActionPerformed(evt);
            }
        });
        kGradientPanel1.add(siUsername);
        siUsername.setBounds(250, 200, 440, 40);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText(bundle.getString("signInOr"));
        kGradientPanel1.add(jLabel3);
        jLabel3.setBounds(450, 480, 50, 20);

        siPassword.setBackground(new Color(0,0,0,0));
        siPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        siPassword.setForeground(new java.awt.Color(153, 153, 153));
        siPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 2, 0, new java.awt.Color(255, 255, 255)));
        siPassword.setCaretColor(new java.awt.Color(255, 255, 255));
        siPassword.setOpaque(false);
        kGradientPanel1.add(siPassword);
        siPassword.setBounds(250, 330, 440, 40);

        btnSignUp.setText(bundle.getString("signInSignUp"));
        btnSignUp.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSignUp.setkBorderRadius(40);
        btnSignUp.setkEndColor(new java.awt.Color(0, 204, 204));
        btnSignUp.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btnSignUp.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSignUp.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btnSignUp.setkStartColor(new java.awt.Color(204, 0, 204));
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnSignUp);
        btnSignUp.setBounds(510, 470, 185, 45);

        btnSignIn.setForeground(new java.awt.Color(204, 204, 204));
        btnSignIn.setText(bundle.getString("signInSignIn"));
        btnSignIn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnSignIn.setkBorderRadius(40);
        btnSignIn.setkEndColor(new java.awt.Color(0, 204, 204));
        btnSignIn.setkHoverEndColor(new java.awt.Color(204, 0, 204));
        btnSignIn.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        btnSignIn.setkHoverStartColor(new java.awt.Color(0, 204, 204));
        btnSignIn.setkStartColor(new java.awt.Color(204, 0, 204));
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });
        kGradientPanel1.add(btnSignIn);
        btnSignIn.setBounds(250, 470, 185, 45);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel5.setText(bundle.getString("signInUsername"));
        kGradientPanel1.add(jLabel5);
        jLabel5.setBounds(250, 160, 100, 27);

        jLabel11.setBackground(new java.awt.Color(255, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(204, 204, 204));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText(bundle.getString("signInLanguages"));
        jLabel11.setToolTipText("");
        kGradientPanel1.add(jLabel11);
        jLabel11.setBounds(780, 10, 80, 20);

        chkBoxMyLocale.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "VI", "EN" }));
        kGradientPanel1.add(chkBoxMyLocale);
        chkBoxMyLocale.setBounds(870, 10, 50, 22);

        ckRememberPass.setBackground(new Color(0,0,0,0));
        ckRememberPass.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        ckRememberPass.setText(bundle.getString("signInRememberPass"));
        ckRememberPass.setBorder(new javax.swing.border.MatteBorder(null));
        ckRememberPass.setOpaque(false);
        kGradientPanel1.add(ckRememberPass);
        ckRememberPass.setBounds(250, 420, 410, 23);

        errPassword.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        errPassword.setForeground(new java.awt.Color(102, 0, 0));
        kGradientPanel1.add(errPassword);
        errPassword.setBounds(250, 390, 440, 30);

        errUsername.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        errUsername.setForeground(new java.awt.Color(102, 0, 0));
        kGradientPanel1.add(errUsername);
        errUsername.setBounds(250, 260, 440, 30);

        btnForgotPassword.setBackground(new Color(0,0,0,0));
        btnForgotPassword.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnForgotPassword.setForeground(new java.awt.Color(102, 102, 102));
        btnForgotPassword.setText(bundle.getString("signInForgotPass"));
        btnForgotPassword.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(0, 0, 0)));
        btnForgotPassword.setOpaque(false);
        kGradientPanel1.add(btnForgotPassword);
        btnForgotPassword.setBounds(340, 560, 220, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 949, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void siUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_siUsernameActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        SignInController siController = new SignInController();
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed

    }//GEN-LAST:event_btnSignUpActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnForgotPassword;
    private keeptoo.KButton btnSignIn;
    private keeptoo.KButton btnSignUp;
    private javax.swing.JComboBox chkBoxMyLocale;
    private javax.swing.JCheckBox ckRememberPass;
    private javax.swing.JLabel errPassword;
    private javax.swing.JLabel errUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JPasswordField siPassword;
    private javax.swing.JTextField siUsername;
    // End of variables declaration//GEN-END:variables


    //hàm hiển thị lỗi password
    public void showErrPassword(String message, Color color) {
        System.out.println(message);
        errPassword.setText(bundle.getString(message));
        errPassword.setForeground(color);
    }

    //hàm hiển thị lỗi username
    public void showErrUserName(String message, Color color) {
        errUsername.setText(bundle.getString(message));
        errUsername.setForeground(color);
    }

    //hàm lấy dữ liệu từ các trường username, password
    public Users getUserLogin() {
        String username = siUsername.getText();
        String password = String.copyValueOf(siPassword.getPassword());
        Users user = new Users(username, password);
        return user;
    }

    //hàm kiểm tra xem dữ liệu có bị trống hay không
    public boolean checkDataField() {
        return (siUsername.getText().equals("") == false
                && siUsername.getText() != null
                && String.valueOf(siPassword.getPassword()).equals("") == false
                && String.valueOf(siPassword.getPassword()) != null);
    }

    //hàm set giá trị cho username và password

    public void setValueUsernameAndPass(String username, String password) {
        siUsername.setText(username);
        siPassword.setText(password);
    }

    //hàm lấy về giá trị true hay false của checkboxremberpassword

    public boolean getValueCheckBoxRememberPassword() {
        return ckRememberPass.isSelected();
    }

    //hàm set value cho checkboxrememberpassword

    public void setValueCheckboxRememberPassword(Boolean check) {
        if (check) {
            ckRememberPass.setSelected(check);
        } else {
            ckRememberPass.setSelected(check);
        }
    }

}
