/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlkh.views;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import qlkh.entities.Unit;
import qlkh.utils.Constants;

/**
 *
 * @author user
 */
public class ReportView extends javax.swing.JPanel {

    /**
     * Creates new form UnitView
     */
    ResourceBundle bundle;

    public ReportView() {
        Locale local = Locale.getDefault();
        setResourceBundle(local);
        initComponents();
    }

    

    // Show view with listUnit on Unit Table
    public void showView() {
        this.setVisible(true);
        

    }
    public JPanel getContent(){
    return this;
    }

    // Set ResourceBundle to this view
    private void setResourceBundle(Locale locale) {
        //Set Resources Bundle theo local 
        bundle = ResourceBundle.getBundle("qlkh/utils/languages", locale);

    }

    // Load list Unit on Unit Table
    public void loadAllUnit(List<Unit> listUnit) {
        DefaultTableModel unitModel = new DefaultTableModel();
        unitModel.setColumnIdentifiers(Constants.HEADER_UNIT_TABLE);
        int startNumber = 1;
        for (Unit unit : listUnit) {
            Vector row = new Vector();
            row.add(startNumber);
            row.add(unit);
               
            row.add((unit.getStatus()>0)?bundle.getString(Constants.STATUS_SHOW):bundle.getString(Constants.STATUS_HIDE));
            startNumber++;
            unitModel.addRow(row);
        }
    }

    // Add event to button addNewUnit
    public void addBtnAddNewUnitActionListener(ActionListener listener) {
    }

    public void addBtnEditUnitActionListener(ActionListener listener) {
    }

  

    public void addBtnDeleteUnitActionListener(ActionListener listener) {
    }

    public void addTableUnitMouseListener(MouseListener listener) {
    }

    // Get text from txtNewUnitField
 
    public void setNewUnitText(String text) {
    }

    public void showMessage(String message, int color) {

    }

    public void focusTxtUnitField() {
    }

   

    public boolean checkUnitName(String unitName) {
        return (unitName != null && unitName.equals("") == false);
    }

    public int showDialogMesage(JFrame frame, String message, String title) {
        return JOptionPane.showConfirmDialog(frame, bundle.getString(message), bundle.getString(title), JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        subPanelLeftOn = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        subPanelRightOn = new javax.swing.JPanel();
        subPanelLeftBelow = new javax.swing.JPanel();
        subPanelRightBelow = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(898, 600));

        subPanelLeftOn.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("Hello");

        javax.swing.GroupLayout subPanelLeftOnLayout = new javax.swing.GroupLayout(subPanelLeftOn);
        subPanelLeftOn.setLayout(subPanelLeftOnLayout);
        subPanelLeftOnLayout.setHorizontalGroup(
            subPanelLeftOnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLeftOnLayout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(149, Short.MAX_VALUE))
        );
        subPanelLeftOnLayout.setVerticalGroup(
            subPanelLeftOnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(subPanelLeftOnLayout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(jLabel1)
                .addContainerGap(147, Short.MAX_VALUE))
        );

        subPanelRightOn.setBackground(new java.awt.Color(51, 153, 0));

        javax.swing.GroupLayout subPanelRightOnLayout = new javax.swing.GroupLayout(subPanelRightOn);
        subPanelRightOn.setLayout(subPanelRightOnLayout);
        subPanelRightOnLayout.setHorizontalGroup(
            subPanelRightOnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        subPanelRightOnLayout.setVerticalGroup(
            subPanelRightOnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        subPanelLeftBelow.setBackground(new java.awt.Color(0, 153, 102));

        javax.swing.GroupLayout subPanelLeftBelowLayout = new javax.swing.GroupLayout(subPanelLeftBelow);
        subPanelLeftBelow.setLayout(subPanelLeftBelowLayout);
        subPanelLeftBelowLayout.setHorizontalGroup(
            subPanelLeftBelowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        subPanelLeftBelowLayout.setVerticalGroup(
            subPanelLeftBelowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        subPanelRightBelow.setBackground(new java.awt.Color(0, 204, 255));

        javax.swing.GroupLayout subPanelRightBelowLayout = new javax.swing.GroupLayout(subPanelRightBelow);
        subPanelRightBelow.setLayout(subPanelRightBelowLayout);
        subPanelRightBelowLayout.setHorizontalGroup(
            subPanelRightBelowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 446, Short.MAX_VALUE)
        );
        subPanelRightBelowLayout.setVerticalGroup(
            subPanelRightBelowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subPanelLeftBelow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subPanelLeftOn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subPanelRightBelow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subPanelRightOn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(subPanelRightOn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subPanelLeftOn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(subPanelLeftBelow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(subPanelRightBelow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel subPanelLeftBelow;
    private javax.swing.JPanel subPanelLeftOn;
    private javax.swing.JPanel subPanelRightBelow;
    private javax.swing.JPanel subPanelRightOn;
    // End of variables declaration//GEN-END:variables
}
