/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qlkh.views;

import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import qlkh.entities.Unit;
import qlkh.utils.Constants;

/**
 *
 * @author user
 */
public class ReportView extends javax.swing.JPanel {

    /**
     * Creates new form UnitView
     */
    ResourceBundle bundle;

    public ReportView() {
        Locale local = Locale.getDefault();
        setResourceBundle(local);
        initComponents();
    }

    

    // Show view with listUnit on Unit Table
    public void showView() {
        this.setVisible(true);
        

    }
    public JPanel getContent(){
    return this;
    }

    // Set ResourceBundle to this view
    private void setResourceBundle(Locale locale) {
        //Set Resources Bundle theo local 
        bundle = ResourceBundle.getBundle("qlkh/utils/languages", locale);

    }

    // Load list Unit on Unit Table
    public void loadAllUnit(List<Unit> listUnit) {
        DefaultTableModel unitModel = new DefaultTableModel();
        unitModel.setColumnIdentifiers(Constants.HEADER_UNIT_TABLE);
        int startNumber = 1;
        for (Unit unit : listUnit) {
            Vector row = new Vector();
            row.add(startNumber);
            row.add(unit);
               
            row.add((unit.getStatus()>0)?bundle.getString(Constants.STATUS_SHOW):bundle.getString(Constants.STATUS_HIDE));
            startNumber++;
            unitModel.addRow(row);
        }
    }

    // Add event to button addNewUnit
    public void addBtnAddNewUnitActionListener(ActionListener listener) {
    }

    public void addBtnEditUnitActionListener(ActionListener listener) {
    }

  

    public void addBtnDeleteUnitActionListener(ActionListener listener) {
    }

    public void addTableUnitMouseListener(MouseListener listener) {
    }

    // Get text from txtNewUnitField
 
    public void setNewUnitText(String text) {
    }

    public void showMessage(String message, int color) {

    }

    public void focusTxtUnitField() {
    }

   

    public boolean checkUnitName(String unitName) {
        return (unitName != null && unitName.equals("") == false);
    }

    public int showDialogMesage(JFrame frame, String message, String title) {
        return JOptionPane.showConfirmDialog(frame, bundle.getString(message), bundle.getString(title), JOptionPane.OK_CANCEL_OPTION, JOptionPane.ERROR_MESSAGE);
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        subPanelLeftUp = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jComboBox2 = new javax.swing.JComboBox();
        subPanelRightUp = new javax.swing.JPanel();
        rightPanel = new javax.swing.JPanel();
        subPanelLeftDown = new javax.swing.JPanel();
        subPanelLefDown = new javax.swing.JPanel();

        mainPanel.setLayout(new javax.swing.BoxLayout(mainPanel, javax.swing.BoxLayout.PAGE_AXIS));

        leftPanel.setBackground(new java.awt.Color(255, 153, 204));
        leftPanel.setLayout(new javax.swing.BoxLayout(leftPanel, javax.swing.BoxLayout.LINE_AXIS));

        subPanelLeftUp.setBackground(new java.awt.Color(255, 153, 51));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout subPanelLeftUpLayout = new javax.swing.GroupLayout(subPanelLeftUp);
        subPanelLeftUp.setLayout(subPanelLeftUpLayout);
        subPanelLeftUpLayout.setHorizontalGroup(
            subPanelLeftUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
            .addGroup(subPanelLeftUpLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        subPanelLeftUpLayout.setVerticalGroup(
            subPanelLeftUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, subPanelLeftUpLayout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        leftPanel.add(subPanelLeftUp);

        subPanelRightUp.setBackground(new java.awt.Color(102, 255, 0));

        javax.swing.GroupLayout subPanelRightUpLayout = new javax.swing.GroupLayout(subPanelRightUp);
        subPanelRightUp.setLayout(subPanelRightUpLayout);
        subPanelRightUpLayout.setHorizontalGroup(
            subPanelRightUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 492, Short.MAX_VALUE)
        );
        subPanelRightUpLayout.setVerticalGroup(
            subPanelRightUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 441, Short.MAX_VALUE)
        );

        leftPanel.add(subPanelRightUp);

        mainPanel.add(leftPanel);

        rightPanel.setBackground(new java.awt.Color(0, 255, 102));
        rightPanel.setLayout(new javax.swing.BoxLayout(rightPanel, javax.swing.BoxLayout.LINE_AXIS));

        subPanelLeftDown.setBackground(new java.awt.Color(0, 255, 255));

        javax.swing.GroupLayout subPanelLeftDownLayout = new javax.swing.GroupLayout(subPanelLeftDown);
        subPanelLeftDown.setLayout(subPanelLeftDownLayout);
        subPanelLeftDownLayout.setHorizontalGroup(
            subPanelLeftDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        subPanelLeftDownLayout.setVerticalGroup(
            subPanelLeftDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        rightPanel.add(subPanelLeftDown);

        subPanelLefDown.setBackground(new java.awt.Color(0, 204, 102));

        javax.swing.GroupLayout subPanelLefDownLayout = new javax.swing.GroupLayout(subPanelLefDown);
        subPanelLefDown.setLayout(subPanelLefDownLayout);
        subPanelLefDownLayout.setHorizontalGroup(
            subPanelLefDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 495, Short.MAX_VALUE)
        );
        subPanelLefDownLayout.setVerticalGroup(
            subPanelLefDownLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 176, Short.MAX_VALUE)
        );

        rightPanel.add(subPanelLefDown);

        mainPanel.add(rightPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 990, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JPanel subPanelLefDown;
    private javax.swing.JPanel subPanelLeftDown;
    private javax.swing.JPanel subPanelLeftUp;
    private javax.swing.JPanel subPanelRightUp;
    // End of variables declaration//GEN-END:variables
}
